import SelectRandomItemsFromArray from '../SelectRandomItemsFromArray'

export const PowersList = [
  'Absorção de Eletricidade',
  'Absorção de energia',
  'Absorção de Raiva',
  'Absorção do Desespero',
  'Acoustikinesis',
  'Adaptação',
  'Aerokinesis',
  'Alteração de Aparência',
  'Armadura avançada',
  'Atmokinesis',
  'Bioeletricidade',
  'Camuflagem',
  'Capacidade de absorver conhecimento',
  'Capacidade de absorver habilidades',
  'Capacidade de alterar a forma',
  'Capacidade de controlar água',
  'Capacidade de controlar animais',
  'Capacidade de controlar antimatéria',
  'Capacidade de controlar ar',
  'Capacidade de controlar aura',
  'Capacidade de controlar campos de força',
  'Capacidade de controlar desintegração',
  'Capacidade de controlar elementos',
  'Capacidade de controlar eletricidade',
  'Capacidade de controlar emoções',
  'Capacidade de controlar energia cósmica',
  'Capacidade de controlar energia escura',
  'Capacidade de controlar energia espiritual',
  'Capacidade de controlar energia mística',
  'Capacidade de controlar energia vital',
  'Capacidade de controlar escuridão',
  'Capacidade de controlar fogo',
  'Capacidade de controlar força universal',
  'Capacidade de controlar gelo',
  'Capacidade de controlar gravidade',
  'Capacidade de controlar ilusões',
  'Capacidade de controlar luz cósmica',
  'Capacidade de controlar luz',
  'Capacidade de controlar magnetismo',
  'Capacidade de controlar matéria escura',
  'Capacidade de controlar matéria exótica',
  'Capacidade de controlar matéria inorgânica',
  'Capacidade de controlar matéria orgânica',
  'Capacidade de controlar mentes',
  'Capacidade de controlar ondas de choque',
  'Capacidade de controlar plantas',
  'Capacidade de controlar plasma',
  'Capacidade de controlar portais dimensionais',
  'Capacidade de controlar probabilidade',
  'Capacidade de controlar quintessência',
  'Capacidade de controlar radiação',
  'Capacidade de controlar sombras',
  'Capacidade de controlar tecnologia',
  'Capacidade de controlar terra',
  'Capacidade de criar campos de força',
  'Capacidade de criar explosões de energia',
  'Capacidade de criar ilusões de água',
  'Capacidade de criar ilusões de ar',
  'Capacidade de criar ilusões de fogo',
  'Capacidade de criar ilusões de terra',
  'Capacidade de criar ondas de choque',
  'Capacidade de criar portais dimensionais',
  'Capacidade de desmaterialização',
  'Capacidade de drenar energia',
  'Capacidade de fundir-se com máquinas',
  'Capacidade de infectar outros com doenças',
  'Capacidade de mudar de aparência',
  'Capacidade de se teleportar para outras dimensões',
  'Capacidade de se teleportar para outros planetas',
  'Capacidade de se teleportar para outros sistemas estelares',
  'Capacidade de se teleportar para outros universos',
  'Capacidade de se tornar intangível',
  'Capacidade de separar a alma do corpo',
  'Capacidade de teletransporte',
  'Capacidade de voar com asas',
  'Capacidades de phasing',
  'Chi',
  'Chronoskimming',
  'Ciberpatia',
  'Clarividência',
  'Conjuração de ilusões',
  'Consciência Cósmica',
  'Controle de fogo',
  'Controle de matéria',
  'Controle de probabilidade',
  'Controle de substâncias químicas',
  'Controle elemental',
  'Controle magnético',
  'Controle mental',
  'Controle temporal',
  'Criação de Buraco Negro',
  'Criação de campos de força',
  'Criação de clones',
  'Criação de hologramas',
  'Criação de ilusões de realidade',
  'Criação de portais',
  'Criação de terremotos',
  'Elasticidade',
  'Electrokinesis',
  'Emissão de ondas de choque',
  'Explosões de energia',
  'Fator de cura',
  'Força do Destino',
  'Geração de ácido acético',
  'Geração de ácido acrílico',
  'Geração de ácido carbônico',
  'Geração de ácido cianídrico',
  'Geração de ácido clorídrico',
  'Geração de ácido cloroacético',
  'Geração de ácido crômico',
  'Geração de ácido fluorídrico',
  'Geração de ácido fórmico',
  'Geração de ácido fosfórico',
  'Geração de ácido nítrico',
  'Geração de ácido perclórico',
  'Geração de ácido sulfônico',
  'Geração de ácido sulfúrico',
  'Geração de ácido tartárico',
  'Geração de ácido',
  'Geração de calor solar',
  'Geração de campos de energia',
  'Geração de campos de força',
  'Geração de campos de som',
  'Geração de Eletricidade',
  'Geração de escuridão',
  'Geração de Frio',
  'Geração de gelo',
  'Geração de hologramas',
  'Geração de ilusões mentais',
  'Geração de ilusões óticas',
  'Geração de raios cósmicos',
  'Geração de raios',
  'Geração de tempestades',
  'Imortalidade',
  'Indução de Raiva',
  'Indução do Desespero',
  'Invisibilidade psíquica',
  'Invisibilidade',
  'Leitura de mentes',
  'Magia do Caos',
  'Manifestação do Desespero',
  'Manipulação de água',
  'Manipulação de animais',
  'Manipulação de antimatéria',
  'Manipulação de aura',
  'Manipulação de calor',
  'Manipulação de campos de força',
  'Manipulação de cópias',
  'Manipulação de desintegração',
  'Manipulação de dimensões',
  'Manipulação de elasticidade',
  'Manipulação de eletricidade',
  'Manipulação de emoções',
  'Manipulação de energia cósmica',
  'Manipulação de energia escura',
  'Manipulação de energia espiritual',
  'Manipulação de energia mística',
  'Manipulação de energia nuclear',
  'Manipulação de energia vital',
  'Manipulação de energia',
  'Manipulação de escuridão',
  'Manipulação de esferas de energia',
  'Manipulação de ferro',
  'Manipulação de força universal',
  'Manipulação de frequência',
  'Manipulação de Frio',
  'Manipulação de gelo',
  'Manipulação de gravidade',
  'Manipulação de ilusões',
  'Manipulação de luz cósmica',
  'Manipulação de luz',
  'Manipulação de magnetismo',
  'Manipulação de matéria escura',
  'Manipulação de matéria exótica',
  'Manipulação de matéria inorgânica',
  'Manipulação de matéria nuclear',
  'Manipulação de matéria orgânica',
  'Manipulação de matéria subatômica',
  'Manipulação de memórias',
  'Manipulação de metal',
  'Manipulação de óleo',
  'Manipulação de ondas de choque',
  'Manipulação de peso',
  'Manipulação de plantas',
  'Manipulação de plasma',
  'Manipulação de portais dimensionais',
  'Manipulação de probabilidade espacial',
  'Manipulação de probabilidade',
  'Manipulação de quarks',
  'Manipulação de quintessência',
  'Manipulação de radiação',
  'Manipulação de realidade',
  'Manipulação de realidades alternativas',
  'Manipulação de replicação',
  'Manipulação de resíduos nucleares',
  'Manipulação de sombras',
  'Manipulação de sonhos',
  'Manipulação de sônico',
  'Manipulação de substâncias radioativas',
  'Manipulação de tecnologia',
  'Manipulação de telecinese',
  'Manipulação de telepatia',
  'Manipulação de terra',
  'Manipulação de vapor',
  'Manipulação de vento',
  'Manipulação de viagem no tempo',
  'Manipulação de vibrações',
  'Manipulação do clima',
  'Manipulação do espaço',
  'Manipulação do Espectro Eletromagnético',
  'Manipulação do som',
  'Manipulação do tamanho',
  'Manipulação do tempo',
  'Mimetismo animal',
  'Percepção da Morte',
  'Poderes Baseados em Arte',
  'Projeção astral',
  'Projeção de energia',
  'Regeneração acelerada',
  'Resistência ao envelhecimento',
  'Sentido de Perigo',
  'Super força',
  'Super inteligência',
  'Telecinese',
  'Telepatia',
  'Teleporte',
  'Teletransporte',
  'Transformação em animais',
  'Transformação',
  'Velocidade sobre-humana',
  'Viagem Dimensional',
  'Viagem no tempo',
  'Visão de calor',
  'Voo',
]

export default function getRandomPowers(quantity: number) {
  return SelectRandomItemsFromArray(PowersList, quantity)
}