import SelectRandomItemsFromArray from '../SelectRandomItemsFromArray'

export const SpeciesList = [
  'Category:Race Categories',
  'Category:Races by Status',
  'Category:Races by Type',
  'A\'askvarii',
  'A-Chiltarians',
  'A.I.M.-Developed Viruses',
  'Aakon',
  'Abilisks',
  'Aboriginal Gods',
  'Absolutes',
  'Abstract Entities',
  'Abyss (Race)',
  'Acanti',
  'Achernonians',
  'Acroyears',
  'Adaptoids',
  'Advanced Virtual Reality Holograms',
  'Adze',
  'Aedians',
  'Aerians (Beast-Men)',
  'Aerwan',
  'Afterlings',
  'Agullo',
  'Ahau',
  'Aimless Ones',
  'Air Elves',
  'Akaana',
  'Akua',
  'Alephs',
  'Alien Mutants',
  'Alligator Men',
  'Alpha Centaurians',
  'Alpha Primitives',
  'Alps (Zombies)',
  'Amatsu-Kami',
  'Amebids',
  'Anansi (Race)',
  'Ancient Aqueos',
  'Ancient Ones',
  'Ancients (Demons)',
  'Angels (Monotheism)',
  'Angels (Tenth Realm)',
  'Angels of Mitra',
  'Annunaki (Aliens)',
  'Annunaki (Deities)',
  'Antelope Men',
  'Anti-Bodz',
  'Antons',
  'Antrons',
  'Ants of the Caramelized Forest',
  'Ape Lords',
  'Ape-Men',
  'Apex (Race)',
  'Apu',
  'Aqueos',
  'Arachnix',
  'Arc Centurians',
  'Archeopians',
  'Archons',
  'Arcturans',
  'Argen',
  'Argorans',
  'Ariguans',
  'Aris',
  'Arms-Men',
  'Arquindae',
  'Arthrosians',
  'Asasabonsam',
  'Asgardian Dragons',
  'Asgardians',
  'Asgardians (Earth-9997)',
  'Aspirants',
  'Asteroid Monsters',
  'Astrans',
  'Astro-Men',
  'Asura (Hindu Demons)',
  'Ataraxians',
  'Atlantean Sea Turtles',
  'Atlanteans (Homo mermanus)',
  'Atomic Puppies',
  'Australopithecus',
  'Australopithecus sediba',
  'Autanians',
  'Autocrons',
  'Axi-Tun',
  'Aylethians',
  'Ba-Bani',
  'Baalists',
  'Babbas',
  'Badoon',
  'Bajang',
  'Balatraans',
  'Baluurians',
  'Bamf (Race)',
  'Banari',
  'Banshees from the Void',
  'Baseline Xartans',
  'Baston-Karians',
  'Bearbarians',
  'Beast-Men (Snow-Apes)',
  'Beastmen',
  'Beasts (Earth-TRN243)',
  'Beginagains, Chosen and Rejects',
  'Bems',
  'Ben\'yr',
  'Berev\'ha Dentii',
  'Betans (Earth-616)',
  'Betans (Earth-7918)',
  'Between (Race)',
  'Beyonders',
  'Bidoceros',
  'Big Rackat',
  'Big-Feet',
  'Bilgesnipes',
  'Biomechanoids',
  'Biphasians',
  'Bird People',
  'Bird-Men (Elder Race)',
  'Bird-Men of Akah Ma\'at',
  'Birdmen (Sunev)',
  'Birdmen (Uranus)',
  'Bitumen Elves',
  'Black Berserkers',
  'Black Light Men',
  'Blasphemous Horror',
  'Blips',
  'Blobs',
  'Blood (Race)',
  'Bloodsucker Plants',
  'Blue Dragons',
  'Blurzz',
  'Boar-Gods',
  'Boboes',
  'Bog Bears',
  'Boggie',
  'Boggy Creek Monsters',
  'Bolovites',
  'Booskans',
  'Borers',
  'Braak\'nhüd',
  'Brain Leeches',
  'Brain Parasites',
  'Breakworldians',
  'Brekk',
  'Brethren',
  'Brine Giants',
  'Brll\'nah Zhhk',
  'Broccoli Men',
  'Brood (Race)',
  'Broodlings of Chthon',
  'Broodskrulls',
  'Brundlebuds',
  'Bruruthianparamecium rex',
  'Brylukas',
  'Bubble-Fish',
  'Builders (Race)',
  'Bull Hulks',
  'Burrow-Squid',
  'Burrower (Atlantean Beast)',
  'Buzzard People',
  'Buzzcrows',
  'Byan\'Nantandu',
  'Calishee',
  'Calurnians',
  'Candy Men',
  'Caretakers',
  'Caretakers (Builders)',
  'Carmondians',
  'Cat Elves',
  'Cat People (Demons)',
  'Cavaranthus Mazorus',
  'Cave Bears',
  'Cave Whales',
  'Celestials',
  'Cellmen',
  'Centauri',
  'Centaurians',
  'Centaurs (Sagittarius)',
  'Centurii',
  'Cerberi',
  'Ch\'i-Lin',
  'Chameloids',
  'Changelings',
  'Chaos Lords',
  'Chaos Sprites',
  'Cheyarafim',
  'Chilarians',
  'Children of Dis',
  'Children of Olokun',
  'Children of Ootah',
  'Children of Rhan',
  'Children of the Sun',
  'Chimeras (Mutants)',
  'China People',
  'Chitauri',
  'Chlorites',
  'Chnitt',
  'Chordai',
  'Chosen (Himalayan)',
  'Chr\'yllites',
  'Chronicoms',
  'Chronosites',
  'Chrrt-chuk',
  'Chupacabras',
  'Ciegrimites',
  'Ciuateteo',
  'Clave',
  'Clavians',
  'Cockroaches',
  'Collective Intelligence',
  'Colony (Otherworld)',
  'Comecogollos',
  'Conglomerate Entity',
  'Connoisseurs',
  'Conqueror Worms',
  'Contraxians',
  'Coral Immortals of Cataracts',
  'Core People',
  'Cotati',
  'Cotatinaught',
  'Courga',
  'Crawlers (Race)',
  'Creatures (Kosmos)',
  'Creatures of the Caves',
  'Critics (Race)',
  'Crystal Warriors',
  'Cu Sith',
  'Cube Men',
  'Curators',
  'Currs',
  'Cyber-Sidhe',
  'Cyclopes',
  'Cygnians',
  'Cygnorians',
  'Cyttora',
  'D\'Arnellians',
  'D\'bari (Race)',
  'D\'Rillians',
  'D\'Sprytes',
  'Daedemon',
  'Daemons',
  'Daevas',
  'Dakkamites',
  'Daleks',
  'Dance',
  'Darbians',
  'Dargallans',
  'Dark Celestials (Horde)',
  'Dark Elves',
  'Dark Gods (K\'ai)',
  'Dark Gods (Narcisson)',
  'Dark Ones (Earth-13519)',
  'Dark Ones (Race)',
  'Darkurians',
  'Dead Men of the Deep',
  'Deathspawn',
  'Deathwings',
  'Degens',
  'Demon Bamfs',
  'Demon People',
  'Demon Servitors',
  'Demon Wolves',
  'Demon-Steeds',
  'Demons',
  'Demons of the Sands',
  'Denuvians',
  'Deonists',
  'Depowered Mutants',
  'Deraxi',
  'Descendants (Race)',
  'Deviant Mutates (Deviant Experiments)',
  'Deviant Mutates (Monstrous Deviants)',
  'Deviant Skrulls',
  'Deviants (Artificial Eternals)',
  'Deviants (Homo descendus)',
  'Deviants of Armechadon',
  'Deviants of Eyung',
  'Deviants of Planet 654.3454.792B',
  'Deviants of Tebbel',
  'Devil-Beasts',
  'Devil-Beasts of Nergal',
  'Devoktites',
  'Diascar',
  'Dievas',
  'Dijiang',
  'Dimension Giants',
  'Dinodroids',
  'Dinosauroids',
  'Dinosaurs',
  'Dirawong',
  'Dire Wraith Salmon Monsters',
  'Dire Wraith/Saurian Hybrids',
  'Dire Wraiths',
  'Direst Wraiths',
  'Divs',
  'Diwatas',
  'Djinn (Race)',
  'Doarj\'nians',
  'Doctopoids',
  'Doctor Moreau\'s Beastfolk',
  'Dominant Species',
  'Dragon Kings (Race)',
  'Dragon-Men',
  'Dragons (Race)',
  'Dragons of K\'un-Lun',
  'Drammoths',
  'Draugr (Race)',
  'Dream Eaters',
  'Drenx',
  'Droomedia Rex',
  'Drop Bears',
  'Druffs',
  'Duckworldians',
  'Dust Daughters',
  'Duvvugoo',
  'Dwarves (Weirdworld)',
  'Dwarves of Nidavellir',
  'Dykkors',
  'Easik (Race)',
  'Echomelians',
  'Een\'Gawori',
  'Een\'gawori Slugs',
  'Ego\'s Anti-bodies',
  'Ekimmu',
  'Elan',
  'Elder Gods of Earth',
  'Elder Gods of Limbo',
  'Elder Ones',
  'Elder Race',
  'Eldrites',
  'Electro-Vampires',
  'Elepheagles',
  'Elves (Weirdworld)',
  'Elves of Otherworld',
  'Elves of the Vale',
  'Endless Resurgence',
  'Endlings',
  'Engels',
  'Ennead',
  'Entemen',
  'Epsiloni',
  'Ergons',
  'Eridani (Race)',
  'Esanaians',
  'Eternal Skrulls',
  'Eternals (Aliens)',
  'Eternals (Homo immortalis)',
  'Eternals of Eyung',
  'Eternals of Planet 654.3454.792B',
  'Eternals of Ron-Shor',
  'Ethereals (Aliens)',
  'Ethereals (Savage Land)',
  'Etholgus-calculus',
  'Evolutionaries',
  'Exo-Parasites',
  'Exolon',
  'Exterminators (Race)',
  'Eyebots',
  'Eyemazons',
  'Eyungs',
  'F\'Saki',
  'Faceless Ones',
  'Failed Augments',
  'Fairies (Nowhere)',
  'Fairies (Otherworld)',
  'Fairies of Asgard',
  'Fallen Stars',
  'Faltine',
  'Faustians',
  'Fearworms',
  'Fenghuang',
  'Ferals',
  'Fernusans',
  'Fhtagn (Race)',
  'Fire Demons of Muspelheim',
  'Fire Giants',
  'Fire-Monsters',
  'Fire-Trolls',
  'Fire-Wasps of the Faltine',
  'Firepedes',
  'Fish People',
  'Fish-Men (Fish Mutates)',
  'Fishmen',
  'Fjord Queens',
  'Flame Men',
  'Flarks',
  'Flatulans',
  'Flb\'Dbi',
  'Flerken',
  'Flock',
  'Flora colossi',
  'Florus Homo',
  'Flying Pythons',
  'Flying Sharks',
  'Flying Trolls of Thryheim',
  'Fmora',
  'Fomalhauti',
  'Fomorians',
  'Forest Devils',
  'Forest Trolls',
  'Fortisquians',
  'Four-Armed Men',
  'Four-Armed Trolls',
  'Fox-People',
  'Freemen (Mojoverse)',
  'Friends',
  'Frogmen',
  'Froma',
  'Frost Beasts',
  'Frost Giants',
  'Fuertonas',
  'Fungi from Yuggoth',
  'Furies (Otherworld)',
  'Glossary:G',
  'Galadorians',
  'Gamarvian Turtles',
  'Glossary:Gamma Mutates',
  'Gamma Spores',
  'Gammaline',
  'Gardeners',
  'Gargoyles (Subterranean Race)',
  'Gegku',
  'Gene Dolls',
  'Gene-Batch',
  'Genetrix',
  'Genius Loci',
  'Genoshan Mutates',
  'Germs (Nowhere)',
  'Gh\'runjians',
  'Ghost Snakes',
  'Ghosts',
  'Ghouls (Subterranean)',
  'Ghouls (Undead)',
  'Giant Moths',
  'Giant Ospreys',
  'Giant Slugs',
  'Giant Slugs (Yann)',
  'Giant Spiders',
  'Giant Squids',
  'Giant Squidsharks',
  'Giants (Hyborian Age)',
  'Giants (Otherworld)',
  'Giants (Viracocha)',
  'Gibborim',
  'Gigantes',
  'Gigantians',
  'Giganto (Atlantean Beast)',
  'Ginnunga-Ghosts',
  'Girafonkeys',
  'Glakorians',
  'Glartrox',
  'Gloomgorians',
  'Gloorthian Death Crabs',
  'Glx',
  'Gnashers',
  'Gnobians',
  'Gnomes (Nine Realms)',
  'Gnomes (Nowhere)',
  'Gnomes (Otherworld)',
  'Gnoph-keh',
  'Goblins (Asgard)',
  'Goblins (Elderspawn)',
  'Goblins (Lilith)',
  'Goblins (Limbo)',
  'Goblins (Otherworld)',
  'Gods of British Guiana',
  'Gods of Earth',
  'Gods of Fandom Mythology',
  'Gods of Latvian Mythology',
  'Gods of the Cosmic Seasons',
  'Gogarrii',
  'Golden People',
  'Golgotha (Race)',
  'Goozotians',
  'Gorankians',
  'Gorgillas',
  'Gorgons',
  'Gortokians',
  'Grad Nan Holt',
  'Gramosians',
  'Great Race of Yith',
  'Greediblix',
  'Green Ones',
  'Greens',
  'Gremlins',
  'Greys',
  'Griffins',
  'Grogronks (Race)',
  'Grosgumbeekians',
  'Grunds',
  'Gryndans',
  'Guna',
  'Gurban',
  'Gurgers',
  'Gynosii',
  'Gyrea',
  'H\'Mojen',
  'H\'ylthri',
  'H\'Zarri',
  'Haab',
  'Haalmhad',
  'Haarg',
  'Haetae',
  'Haffensye',
  'Haif-Nas',
  'Haifs',
  'Hairy Ones',
  'Haizli',
  'Half-Men',
  'Halfworlders',
  'Hamadryads',
  'Hanon Tramps',
  'Harpies (Elderspawn)',
  'Harpies (Olympus)',
  'Hauk\'ka',
  'Hawksquatches',
  'Headless Cattle',
  'Hedzek',
  'Hel-Snakes',
  'Hellbent',
  'Hellhounds (Race)',
  'Herms',
  'Hesperides',
  'Hexopuses',
  'Hibers',
  'Hidden Ones (Earth-616)',
  'Category:High Temperature Races',
  'Highbreeds',
  'Hiisi',
  'Hill Monkeys',
  'Hill People',
  'Hkkkt',
  'Hlavac Virus',
  'Hoar-Frost Ogres',
  'Hobomokko',
  'Hodinns',
  'Hodomurians',
  'Hoggothian Giants',
  'Hollering Things',
  'Homeworlders',
  'Homicide Crabs',
  'Homo antecessor',
  'Homo erectus',
  'Homo habilis',
  'Homo insectus',
  'Honchi (Race)',
  'Hordax',
  'Horde (Race)',
  'Horsemen\'s Steeds',
  'Horusians',
  'Houdaks',
  'Hound-Hawks',
  'Hounds (Mutants)',
  'Hounds of Tindalos',
  'Hreytions',
  'Hrollën',
  'Hujah',
  'Hulks (Earth-96099)',
  'Human Spiders (Homo arachnus)',
  'Human-Qys Hybrids',
  'Humanoid Felinigen Mark Two',
  'Humans',
  'Humans (Homo sapiens)',
  'Hurctarians',
  'Huskie',
  'Hydra (Parasites)',
  'Hydras',
  'Hydreka',
  'Hyginians',
  'Hypergods',
  'Hypno-Fish',
  'Hyssta',
  'I\'Thans',
  'Ibeji (Race)',
  'Ice Dwarves',
  'Ice Elves',
  'Ice Giants',
  'Ice Hounds',
  'Ice People',
  'Ice Trolls',
  'Ice Worms',
  'Ice-Devils',
  'Ichthyosaurs',
  'Category:Races by Identity',
  'Imps',
  'Inaku (Race)',
  'Incentaurians',
  'Incinerators',
  'Incubi',
  'Indigarrians',
  'Infinites (Cosmic Beings)',
  'Infra-Worlders',
  'Inhuman Dogs (Inhomo canis lupus familiaris)',
  'Inhumans (Inhomo supremis)',
  'Insect Men',
  'Insect-Men',
  'Insectivorids',
  'Insecto-trolls',
  'Interdimensional Bacteria',
  'Interdites',
  'Inua',
  'Inupasugjuk',
  'Iron-Bots',
  'Ixhoohxi',
  'Jath\'che',
  'Jeriens',
  'Jetmen',
  'Jiangshi',
  'Jiggle-Os',
  'Jinn (Nine Realms)',
  'Jiuweihu',
  'Jovians (Aliens)',
  'Jovians (Humans)',
  'Judans',
  'Jumala',
  'Jupiterian Sauro-Beast',
  'Jutefiosk',
  'K\'aitians',
  'K\'choqtoc',
  'K\'Lanti',
  'K\'rithians',
  'K\'yndarii',
  'Kaddak',
  'Kalimachh',
  'Kallusians',
  'Kamado',
  'Kaptroids',
  'Karidians',
  'Kawa',
  'Keepers',
  'Kelozyn',
  'Kentauros',
  'Kestorans',
  'Khats',
  'Kiffs',
  'Kigor (Aliens)',
  'Killcrops (Mutants)',
  'Killform (Earth-1610)',
  'Kirithiril',
  'Kith',
  'Kkallakki',
  'Klangians',
  'Klantorr',
  'Klklk',
  'Klyruvians',
  'Knobbies',
  'Knsashii',
  'Ko-Kri',
  'Kobarians',
  'Kodabaks',
  'Korbinites',
  'Kosmosians',
  'Kraawls',
  'Kraken (Race)',
  'Kramen',
  'Kree',
  'Kree Deviants',
  'Kree Eternals',
  'Kree Sentries',
  'Kree-Kowl',
  'Krill (Gamma Mutates)',
  'Krill (Race)',
  'Kronans',
  'Krook',
  'Krozzar',
  'Kryihd',
  'Krylorians',
  'Kt\'kn',
  'Kumiho',
  'Kymellians',
  'Lakhmu',
  'Lamais',
  'Lamia (Race)',
  'Land Sharks',
  'Landlaks',
  'Lard Giants',
  'Latents of Eyung',
  'Lava Colossi',
  'Lava Men',
  'Lavorites',
  'Laxidazians',
  'Lem',
  'Lemurians (Homo mermanus)',
  'Leopards',
  'Leprechauns',
  'Leprechauns of Cassidy Keep',
  'Lesser Old Ones',
  'Levians',
  'Leviathans (Chitauri)',
  'Leviathon Servitors',
  'Leviathons',
  'Licorice Men',
  'Light Elves',
  'Light-Forms',
  'Lilin',
  'Lilliputians',
  'Lilîtu',
  'Limbic Infundibula',
  'Limbos',
  'Linneas',
  'Linstra',
  'Lion-People',
  'Lithodia Rexians',
  'Living Shadows',
  'Living Vampires',
  'Lizard Men (Deviants)',
  'Lizard Men (Iranda)',
  'Lizard Men of Tok',
  'Lizard Men of Vala-Kuri',
  'Lizardmen',
  'Loa (Vodū)',
  'Lobster People',
  'Loci',
  'Logarans',
  'Long Fangs',
  'Lorq',
  'Luareians',
  'Ludberdites',
  'Lumina (Race)',
  'Lumlyans',
  'Luna-Things',
  'Lunanimals',
  'Lunarians',
  'Lung Dragons',
  'Lupak',
  'Luphomoids',
  'Lupine',
  'Lycans',
  'M\'Hassians',
  'M\'ndarrel',
  'M\'Ndavians',
  'M\'Rellik',
  'M\'Rglots',
  'Mabdhara',
  'Mad Folk',
  'Magma Men',
  'Mahars',
  'Majesdanians',
  'Makers (Race)',
  'Makluans',
  'Mala (Race)',
  'Mall-Trolls',
  'Mammoths',
  'Man-Bats of Ur-Xanarrh',
  'Man-Serpents',
  'Man-Things',
  'Man-Wolves',
  'Manchester Gods',
  'Mandate',
  'Mandos',
  'Mandroid (Kree)',
  'Manidoog',
  'Manifestations',
  'Mannequins',
  'Manphibians',
  'Manticores',
  'Mantracorians',
  'Manufactured Harmonites',
  'Many-Souled Ones',
  'Mares',
  'Martian Masters',
  'Martians (Race)',
  'Marvanites',
  'Mawkaw Magkong',
  'Mazikim',
  'Meat-Forms',
  'Medusae',
  'Megalodons',
  'Megans',
  'Mekkans',
  'Melnibonéans',
  'Men-Fish',
  'Mentelleronites',
  'Mephitisoids',
  'Mercurians (Aliens)',
  'Mercurians (Humans)',
  'Mermaids',
  'Metal Men of the Moon',
  'Metamutants',
  'Meteor Men',
  'Metroliths',
  'Midassians',
  'Mim Unit',
  'Mind Maggots',
  'Mind Web',
  'Mindful Ones',
  'Mindless Ones',
  'Minotaurs',
  'Minute Men (Nowhere)',
  'Mitans',
  'Mobians',
  'Moca Vampires',
  'Moensiens',
  'Mokele-Mbembe',
  'Moksgm\'ol',
  'Molans',
  'Mole Men (Race)',
  'Mole People',
  'Moloids',
  'Monsters (Dream Realm)',
  'Monsters of Badoon',
  'Moon Elves',
  'Moonchildren',
  'Moonmen',
  'Moord (Inhuman Badoon)',
  'Morani',
  'Morbific Ghouls',
  'Mosquito Men',
  'Mountain Giants',
  'Mox-Pox',
  'Muck Sharks',
  'Mugabee',
  'Mugrats',
  'Multi-Tusked Elephants',
  'Mummudrai',
  'Mundusians',
  'Musculans',
  'Muspelheim Firesharks',
  'Mutant Brood',
  'Mutant Cats',
  'Mutant Crocodiles',
  'Mutants (Homo superior)',
  'Mutroids',
  'Muttaliku',
  'Muurks',
  'Myndai',
  'N\'Galans',
  'N\'Garai',
  'N\'Grith',
  'Nanda (Race)',
  'Neanderthals (Homo neanderthalensis)',
  'Neganatives',
  'Neo (Race)',
  'Neo-Apes',
  'Neo-Hyde Gutspawn',
  'Neo-Men',
  'Nephilim',
  'Nephilites',
  'Neptunians',
  'Neptunus (Atlanteans)',
  'Nereids',
  'Nethergods',
  'Netherworlders',
  'Netredi',
  'Neuri',
  'New Folk',
  'New Men',
  'Neyaphem',
  'Nhu\'Ghari',
  'Nicanthans',
  'Night Beasts',
  'Nightgaunts',
  'Nilffim',
  'Nioth Kargai',
  'Nogus',
  'Non-Human Mutants',
  'Norns (Gods)',
  'Norrak',
  'Nowlanians',
  'Nullans',
  'Nuwali',
  'Nymenians',
  'Nymphs',
  'Octo-Meks',
  'Octo-Squid',
  'Octopus-Men (Earth)',
  'Octopus-Men (Neptune)',
  'Ogdoad',
  'Ogres (Nine Realms)',
  'Ogres (Otherworld)',
  'Ogres (Weirdworld)',
  'Old Ones (City of the Winged One)',
  'Olettas',
  'Olympians',
  'Omnophage',
  'Onees',
  'Ongulians',
  'Oni (Horned Ogres)',
  'Oobagonians',
  'Oolafat',
  'Ophions',
  'Oranois',
  'Orcs',
  'Oriental Giants',
  'Orloni',
  'Orthoxalith',
  'Other Gods',
  'Outer Gods',
  'Outriders (Race)',
  'Ovi (Race)',
  'Ovoids',
  'P!ndyr',
  'P\'qui',
  'P\'Tah',
  'Pah Ree',
  'Pangorians',
  'Panspermians',
  'Category:Pantheons',
  'Category:Pantheons of Earth',
  'Pao\'Ree',
  'Parrot-Men',
  'Patupaiarehe',
  'Pegasi',
  'Pegasusians',
  'Pelagians',
  'People of the Black Jewel',
  'People of the Black Sea',
  'People of the Dust',
  'Phalanx (Race)',
  'Phaznozzes',
  'Pheragots',
  'Phooka',
  'Phorusrhacidae',
  'Phrox',
  'Phytons',
  'Pikaia',
  'Pixies',
  'Category:Races by Place of Origin',
  'Plasmagenians',
  'Pleasure Elves',
  'Plesiosaurs',
  'Plodex',
  'Plutonians',
  'Pluvians',
  'Poisons',
  'Polemachians',
  'Pool-Dwellers',
  'Poppupians',
  'Positpeople',
  'Possessors',
  'Post-Humans (Homo novissima)',
  'Post-Ragnarök Humans',
  'Prashardians',
  'Predator X',
  'Predators (Earth-928)',
  'Primal Gods (Disambiguation)',
  'Prime Skrulls',
  'Primeans',
  'Procyonites',
  'Proemial Gods',
  'Progenitors',
  'Progeny',
  'Proselytes',
  'Prosilicans',
  'Protar',
  'Proto-Mutants',
  'Psi Centarians',
  'Psycho-Wraith',
  'Pterolyths',
  'Pterons',
  'Pterosaurs',
  'Puffball',
  'Pyronanos',
  'Pythians',
  'Qalupalik',
  'Qilin',
  'Qlippoth',
  'Qrii',
  'Quadroceratops',
  'Quarlians',
  'Quarrn',
  'Queega',
  'Quicksand Squids',
  'Quinnten',
  'Quists',
  'Quo Modari',
  'Quokrillians',
  'Quons (Species)',
  'Quwrlln',
  'R\'malk\'i',
  'R\'Vaalians',
  'R\'zahnians',
  'Category:Races by Era',
  'Category:Races by Location',
  'Category:Races by Physical Features',
  'Category:Races of Deities',
  'Raj-Lek',
  'Rajaks',
  'Rakasha',
  'Rakshasa',
  'Ralfzz',
  'Raptors (Race)',
  'Ravarati',
  'Category:Races by Reality',
  'Reapers (Race)',
  'Red Dragons',
  'Reincarnated Skeletons',
  'Remnants (Race)',
  'Remorath',
  'Reptile Men',
  'Reptoids',
  'Reptos',
  'Rescorlans',
  'Resillians',
  'Rhinosaurs',
  'Rhunians',
  'Riding Cats',
  'Rigellian Recorders',
  'Rigellians',
  'Rime Giants',
  'Roboids',
  'Rock Giants',
  'Rock Tribe',
  'Rock Trolls (Orange-Skinned)',
  'Rocktoids',
  'Roclites',
  'Ru\'Tai',
  'Rubber People',
  'Rumati',
  'Ruu\'lto',
  'S\'raphh',
  'Sagittarians',
  'Sakaaran Dragons',
  'Sakaaran Imperials',
  'Sakaaran Natives',
  'Sakaarans',
  'Samjokgu',
  'Sand Devil (Hyboria)',
  'Sand Devils',
  'Sand Sharks',
  'Sand Tigers',
  'Sarks',
  'Sasquatch (Race)',
  'Satanians',
  'Satori',
  'Saturnians',
  'Satyrs',
  'Saurians',
  'Saurids',
  'Savage Elves (Weirdworld)',
  'Scadamites',
  'Scaldings',
  'Scalluscs',
  'Scania',
  'Scatter (Race)',
  'Scavengers (Race)',
  'Scorpeople',
  'Scorpians',
  'Screamies',
  'Scy\'ar Tal',
  'Sea Elves',
  'Sea Serpents',
  'Seal People',
  'Security Daemons',
  'Selkies',
  'Sentimault',
  'Sentinel Hounds',
  'Sentinex',
  'Serpent-Men',
  'Severians',
  'Sha\'Barri',
  'Shadow (Atlantean Beast)',
  'Shadow Giants',
  'Shadow Goblins',
  'Shadow Nixes',
  'Shadow People',
  'Shadowbeings',
  'Shadowmen of Kaa-U',
  'Shaggy Men',
  'Shaper of Worlds Subjects (Race)',
  'Shark Men',
  'Shark People',
  'Sharks from Beyond Time',
  'She-Serpents',
  'Shedu',
  'Sheenarians',
  'Shi\'ar (Race)',
  'Shi\'ar Giants',
  'Shilleths',
  'Shin (Korean Gods)',
  'Shining Ones (Elder Race)',
  'Shinma (Demons)',
  'Shoggoths',
  'Shottz',
  'Shrike (Race)',
  'Shrinks/Loonies',
  'Sidhe (Otherworld)',
  'Sidri',
  'Silbens',
  'Silent Ones (Earth-616)',
  'Silent Ones (Trolls)',
  'Simbi',
  'Sinalinas',
  'Sinnarians',
  'Sirenas',
  'Sirens',
  'Sirens (War of the Worlds)',
  'Sirians',
  'Siris',
  'Sirrush',
  'Sirusites',
  'Sivians',
  'Six-Legged Monkeys',
  'Ska\'r',
  'Skard',
  'Skifflefuffles',
  'Skirri',
  'Skrull Mutants',
  'Skrullduggers',
  'Skull Men',
  'Skulora',
  'Skunk Ape (Race)',
  'Sky Lords of Indigarr',
  'Slavers (Race)',
  'Sleepers (Arctilan)',
  'Sleepwalkers',
  'Sligs',
  'Sloggs',
  'Slorgs',
  'Slototh\'s Minions',
  'Sm\'ggani',
  'Smilodon',
  'Smoke Elves',
  'Smokeworlders',
  'Snake-People (Children of Ishiti)',
  'Snakes of Many Colors',
  'Snarfs',
  'Snatmen',
  'Snats',
  'Sneepers',
  'Snow Apes',
  'Snow Tigers',
  'Snow Wyrms',
  'Snow-Leopards',
  'Snow-Lions',
  'Snowmen',
  'Solons',
  'Sonneillon (Demons)',
  'Soul Beasts',
  'Soul-Eaters',
  'Sovereign (Race)',
  'Space Beasts',
  'Space Demons',
  'Space Phantoms',
  'Space Squids',
  'Space-Lubbers',
  'Sparkitects',
  'Spartax (Race)',
  'Spartoi',
  'Spawn of the Dark Gods',
  'Specto-Fish',
  'Spectral Cannibal Trolls',
  'Spheroids',
  'Spice Elves',
  'Spider Men',
  'Spider-Men (Aliens)',
  'Spider-People (Elderspawn)',
  'Spider-Totems',
  'Spiders',
  'Spiders of Hel',
  'Spikes (Race)',
  'Spindlies',
  'Spineless Ones',
  'Spirit Drinker (Earth-92131)',
  'Spirits of the Trees',
  'Sprites',
  'Spyricans',
  'Sssth',
  'Star-Headed Old Ones',
  'Stark (Race)',
  'Stark-Self',
  'Starmen',
  'Starnaris',
  'Starsharks',
  'Stenth (Race)',
  'Stonians',
  'Storm Colossi',
  'Storm Giants',
  'Strontians',
  'Stygians (Aliens)',
  'Stymphalian Birds',
  'Sub-Earth Men',
  'Category:Sub-Zero Races',
  'Succubi',
  'Sunbeast',
  'Super-Inhumans',
  'Swamp Adders',
  'Swamp Apes',
  'Swamp Mammoths',
  'Swamp Whales',
  'Syllth',
  'Symbioids',
  'Symbionts',
  'Symbiote Dragons',
  'Symbiote Slayers',
  'Symbiotes',
  'Symqua',
  'Taa-ans',
  'Talbosians',
  'Taniwha',
  'Taotie',
  'Taqriaqsuit',
  'Taurians',
  'Tcho-Tcho',
  'Technarchy',
  'Teeny-Weeny People',
  'Tektons',
  'Teku-Maza',
  'Tele-Fish',
  'Temploids',
  'Temporal Ghasts',
  'Temporalon',
  'Tenger',
  'Tengu (Devils)',
  'Termids',
  'Terminex',
  'Termini',
  'Terra Forms',
  'Terrible Brain Voles',
  'Terrors',
  'Teuthidans',
  'Tezcatlipoca\'s Giants',
  'Thaloomians',
  'Therhin',
  'Thermophile Litometallovores',
  'Things (Battleworld)',
  'Throlls',
  'Thunderbird (Giizhigong)',
  'Thuvrians',
  'Tiding-flies',
  'Tigagators',
  'Tigers',
  'Tigers of the Titans',
  'Timber Giants',
  'Time Eaters',
  'Time Gods',
  'Time-Keepers',
  'Time-Twisters',
  'Timebreakers',
  'Tipua',
  'Tirenians',
  'Titans (Eternals)',
  'Titans (Olympians)',
  'Toraxisi',
  'Tordenkakerlakk',
  'Torfans',
  'Traanians',
  'Tree People',
  'Tribbitites',
  'Tribe Jiu Li',
  'Tribellians',
  'Tribunals',
  'Trill',
  'Trinarians',
  'Trionians',
  'Troids',
  'Troll Gods',
  'Trolls (Otherworld)',
  'Trolls of Hades',
  'Troxx',
  'Troyjans',
  'True Faeries (Old Ones)',
  'Tryks',
  'Tsiln',
  'Tsum Tsum',
  'Tsyrani',
  'Tuatha de Danaan',
  'Tubanti',
  'Turek',
  'Turpalurpalurpa\'todians',
  'Tusk-Bears',
  'Tuurngait',
  'Tyannans',
  'Tyclosians',
  'Tyrannoids',
  'Tyrannosaurus rex',
  'Tzin',
  'Tēteoh',
  'U\'sr\'prians',
  'Uboongi',
  'Uhari',
  'Ul\'lula\'ns',
  'Ultimos (Race)',
  'Ultroids',
  'Unbreathing',
  'Uncarians',
  'Uncreated (Aliens)',
  'Underdwellers',
  'Underearth Men',
  'Undergods',
  'Undergrounders (Race)',
  'Undersea Titans',
  'Underwater Apes',
  'Undines',
  'Undying Ones',
  'Unicorns',
  'Unoorion Egg-layers',
  'Unseen (Aliens)',
  'Category:Unseen Races',
  'Uqot',
  'Uranians',
  'Uranosians',
  'Uranusians',
  'Urgeld',
  'Urmut',
  'Urrpo-Fish',
  'Urrulians',
  'Ursaa',
  'Uruburians',
  'Utopians (Race)',
  'Va-Shaak',
  'Vacuum Beast',
  'Val\'Gyrr',
  'Vampa-Cabras',
  'Vampires',
  'Vanir (Gods)',
  'Vanyan',
  'Vedomi',
  'Vegans (Race)',
  'Vellus-Karians',
  'Venturites',
  'Venusian Retriever-Anemone',
  'Venusian Shock-Flies',
  'Venusians',
  'Vescora',
  'Vi-Locks',
  'Vibranium Mutates',
  'Vie Myrh',
  'Viscardi (Race)',
  'Vodū',
  'Voldi',
  'Vontsalvants',
  'Voodoo Demons',
  'Vorms',
  'Voxiplode',
  'Vrakanin',
  'Vrellnexians',
  'Vril (Race)',
  'Waidians',
  'Wairua',
  'Walkers of the Outer Void',
  'Walrus Men',
  'War Faeries of Wendigorge',
  'Warpies (Race)',
  'Warpsmiths',
  'Warrior-Rats',
  'Warskrulls',
  'Warthos',
  'Warwolves',
  'Watch-Dragons',
  'Watchers',
  'Water Elementals',
  'Wendigo (Race)',
  'Were-Bugs',
  'Were-Fish',
  'Were-Honey-Badgers',
  'Were-Lampreys',
  'Were-Men',
  'Were-Octopi',
  'Were-Rhinoceros',
  'Were-Roosters',
  'Were-Slugs',
  'Were-Snakes',
  'Werewolves',
  'Whirldemons',
  'White Apes',
  'White Room (Inhuman Kymellians)',
  'Whynnm',
  'Wilameanis',
  'Wild Men of the Woods',
  'Wild Toad Men',
  'Wild Worms',
  'Wildebots',
  'Wind Giants',
  'Wing Mark',
  'Winged Horses',
  'Winged Ones (Ytitnedion)',
  'Winged Zebras',
  'Witchfinder Wolves',
  'Wizard Race',
  'Wobbow',
  'Wobbs',
  'Wolf Gods',
  'Wolf Men',
  'Wolves of K\'un-Lun',
  'Woods Boogers',
  'Wraith Whales',
  'Wugin',
  'Wyrmspawn',
  'Wyverns',
  'Xandarian Snails',
  'Xandarians',
  'Xantareans',
  'Xantha',
  'Xanthian Boulder-Crushers',
  'Xartan Deviants',
  'Xem',
  'Xenians',
  'Xenophage',
  'Xeronians',
  'Xian (Race)',
  'Xixix',
  'Xorrians',
  'Xreeks',
  'Y\'lestja',
  'Yazatas',
  'Category:Races by Year of Debut',
  'Yellow-Crested Titans',
  'Yeren',
  'Yersinia pestis',
  'Yeti (Race)',
  'Ygothic Cyclopeans',
  'Yiki Onna',
  'Yirbek',
  'Yrds',
  'Yrrl Beasts',
  'Z\'lyztayans',
  'Z\'nox (Race)',
  'Zarkons',
  'Zemadar',
  'Zen-Whoberis',
  'Zenn-Lavians',
  'Zennans',
  'Zephyreans',
  'Zhynn',
  'Ziffifers',
  'Zimbumblers',
  'Zmbuku',
  'Zn\'rx',
  'Zola\'s Mutates',
  'Zombies',
  'Zundamites',
  'Zygotian Zingfop',
  'Zyndarian',
]


export default function getRandomSpecies(quantity: number) {
  return SelectRandomItemsFromArray(SpeciesList, quantity)
}