import SelectRandomItemsFromArray from '../SelectRandomItemsFromArray'

export const TeamsList = [
  'A-Force',
  'Aniquiladores',
  'Cavaleiros de Wundagore',
  'Defensores Secretos',
  'Esquadrão Supremo',
  'Estrangeiros',
  'Eternos',
  'Excalibur',
  'Exército de Frankenstein',
  'Fabulosos Vingadores',
  'Falcão e Soldado Invernal',
  'Fugitivos',
  'Fúria Jovem',
  'Futuros Vingadores',
  'Guarda do Infinito',
  'Guardiões da Galáxia',
  'I.M.A.',
  'Illuminati',
  'Impossíveis X-Men',
  'Inumanos',
  'Irmandade de Mutantes',
  'Irmandade de Vingança',
  'Irmãos do Martelo',
  'Irmãos Inumanos',
  'Jovens Vingadores',
  'Novos Guerreiros',
  'Novos Vingadores',
  'Ordem Negra',
  'Os Defensores',
  'Os Doze Sóis',
  'Os Doze',
  'Os Imortais',
  'Os Novos Mutantes',
  'Os Vingadores',
  'Poderosos Vingadores',
  'Quarteto Fantástico',
  'Renegados',
  'S.H.I.E.L.D.',
  'Sindicato Sinistro',
  'Slingers',
  'Sociedade da Serpente',
  'Supremos',
  'Thunderbolts',
  'Tropa Alfa',
  'Vingadores da Cidadela',
  'Vingadores da Costa Leste',
  'Vingadores da Costa Oeste',
  'Vingadores da Década de 1950',
  'Vingadores da Século 31',
  'Vingadores Jovens',
  'Vingadores Secretos da S.H.I.E.L.D.',
  'Vingadores Secretos',
  'Vingadores Selvagens da Costa Oeste',
  'Vingadores Selvagens',
  'Vingadores Sombrios de S.H.I.E.L.D.',
  'Vingadores Sombrios',
  'Vingadores Subterrâneos',
  'Vingadores X',
  'X-Club',
  'X-Factor A.I.M.',
  'X-Factor Aniquiladores',
  'X-Factor Cavaleiros de Wundagore',
  'X-Factor Clássico',
  'X-Factor Estrangeiros',
  'X-Factor Exército de Frankenstein',
  'X-Factor Fabulosos Vingadores',
  'X-Factor Falcão e Soldado Invernal',
  'X-Factor Fúria Jovem',
  'X-Factor Guerreiros Secretos',
  'X-Factor I.M.A.',
  'X-Factor Impossíveis X-Men',
  'X-Factor Investigations',
  'X-Factor Irmandade de Vingança',
  'X-Factor Irmãos Inumanos',
  'X-Factor Ordem Negra',
  'X-Factor Os Doze Sóis',
  'X-Factor Os Doze',
  'X-Factor Os Imortais',
  'X-Factor Os Novos Mutantes',
  'X-Factor Poderosos Vingadores',
  'X-Factor Sindicato Sinistro',
  'X-Factor Sindicato-X',
  'X-Factor Slingers',
  'X-Factor Sociedade da Serpente',
  'X-Factor Tropa Alfa',
  'X-Factor Vingadores Secretos',
  'X-Factor Vingadores',
  'X-Factor X-Club',
  'X-Factor X-Force X-Táticos',
  'X-Factor X-Force',
  'X-Factor X-Inumanos',
  'X-Factor X-Men Azuis',
  'X-Factor X-Men Dourados',
  'X-Factor X-Men Verdes',
  'X-Factor X-Men Vermelhos',
  'X-Factor X-Men',
  'X-Factor X-Táticos',
  'X-Factor X-Terminadores',
  'X-Factor',
  'X-Force',
  'X-Men Azuis',
  'X-Men Dourados',
  'X-Men Verdes',
  'X-Men Vermelhos',
  'X-Men',
  'X-Statix',
  'X-Táticos',
  'X-Terminadores',
  'X-Treme X-Men',
]


export default function getRandomTeams(quantity: number) {
  return SelectRandomItemsFromArray(TeamsList, quantity)
}